spring.application.name=citas_salud
spring.datasource.url=jdbc:postgresql://localhost:5432/centro_salud
spring.datasource.username=postgres
spring.datasource.password=ImaGine54ww!

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8080